version: '3.8'

services:
  app:
    image: 074360085669.dkr.ecr.ca-central-1.amazonaws.com/transit-route-planner-backend:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=transit_route_planner
    depends_on:
      - db
    command: sh -c "npm run create:seed:db && npm start"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=transit_route_planner
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: